### ISSUE TITLE
[REQ] Support for non-GamePad controllers

### ISSUE THREAD

**Issue by vaguerant** [PretendoNetwork/Nimble#2]
Just for convenience's sake, being able to use the Nimble patcher with non-GamePad controllers would be nice. Not everyone has a functioning GamePad, and when they do it's not always "around" (mine sits in its cradle on the coffee table if I'm using other controllers).

Wiimote and Pro Controller seem most essential, with Classic Controller further down the priority list, but might as well be added if the others are.

**Comment by QuarkTheAwesome** [comment]
Nimble is focusing on Tiramisu, which doesn't require controllers of any kind at all.
