### ISSUE TITLE
Always doing OSDynload_Acquire for nn_olv might alter memory layout

### ISSUE THREAD

**Issue by Maschell** [PretendoNetwork/Nimble#9]
The title patcher [always acquires the nn_olv](https://github.com/PretendoNetwork/Nimble/blob/cd42ec81dde08aac4657ca3cc6870e886caae0ef/title_patcher/source/entry.c#L126) which might change the memory layout and cause problems/crashes for certain games. 

It would be better to check if the .rpl is actually loaded (See `OSDynLoad_IsModuleLoaded` and `OSDynLoad_AddNotifyCallback`) instead of always loading it

**Comment by ashquarky** [comment]
The intent is to pre-empt games that are using DynLoad, but you're right that `AddNotifyCallback` is the correct solution, assuming games don't do anything weird like deleting all the callbacks. Also applies to Inkay

**Comment by Maschell** [comment]
> unless there's a particular game that's not working.
Apparently Hyrule Warrior is broken: https://www.reddit.com/r/WiiUHacks/comments/11iut7k/i_am_geting_this_error_then_i_start_hyrule/

**Comment by Maschell** [comment]
Another example of Nimble breaking a game:
https://gbatemp.net/threads/exception-dsi-launching-watch-dogs-with-tiramisu-and-other-problems.631946/

**Comment by ashquarky** [comment]
We're actually in the process of phasing out Nimble entirely and are now only supporting Inkay, just waiting for the documentation to catch up on that. So our official answer to such issues from here is going to be installing Aroma and using Inkay.

If there are games broken by Inkay we will definitely investigate those.

**Comment by ashquarky** [comment]
Title patcher is no longer in use
